name: Solidity Compile

on:
  push:
    branches:
      - main
      - cleanup
      
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Solidity Compilation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Compile Solidity contracts
        run: npm hardhat compile