name: Solidity Compile

on:
  push:
    branches:
      - main
      - cleanup
      
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Solidity Compilation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Compile Solidity contracts
        uses: ethers-io/solidity@v1
        with:
          solc-version: '0.7.0'  # Adjust to your desired Solidity version
          contracts: './Contracts/**/*.sol'  # Adjust the path to your Solidity contracts
