name: Solidity Compile

on:
  push:
    branches:
      - main
      - cleanup
      
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Solidity Compilation
    runs-on: ubuntu-latest
    steps:
     - name: Make envfile
       uses: SpicyPizza/create-envfile@v1
       with:
        envkey_private_key: '0000000000000000000000000000000000000000000000000000000000000001'
        file_name: .env

     - name: Checkout code
       uses: actions/checkout@v2

     - name: Install Node.js and yarn
       uses: actions/setup-node@v2
       with:
        node-version: '18.16.0'
        cache: 'yarn'

     - name: Install dependencies
       run: yarn install

     - name: Compile Solidity contracts
       run: yarn hardhat compile